language: scala
scala: 2.11.7
notifications:
  slack:
    rooms:
      - plasticine-arch:kRp0KfrygHiq2wCMrcgMogBW#regression
  email:
    recipients: mattfel@stanford.edu
    on_success: change # default: change
    on_failure: always # default: always
# branches:
#   only:
#   - fpga
#   - master
install: 
  - wget https://www.veripool.org/ftp/verilator-3.900.tgz
  - unset VERILATOR_ROOT  # For bash
  - tar xvzf verilator*.t*gz
  - cd verilator*
  - ./configure
  - make
  - sudo make install
before_script:
  - sudo chmod +x /usr/local/bin/sbt # Travis is being so annoying (https://github.com/travis-ci/travis-ci/issues/7703)
  - cd ${NEW_TEMPLATES_HOME}
script: 
  - free -k
  - bash ./run-templates.sh all
  - sbt "test:runMain templates.Launcher all"
  - cd /home/travis/build/stanford-ppl/spatial/
  - sbt compile
